Awesome books JavaScript class
ntimanu/Awesome-books-project pull request #2
Opened 2023-06-15 19:33 UTC by ntimanu

In this branch I :

- Created class methods to add and remove books.
- Added CSS styles to the application

![PULLREQUEST](https://github.com/ntimanu/Awesome-books-project/assets/96081355/a1c98a16-d1b5-496c-87d7-a96e74e6fbb8)

2023-06-15 19:48 UTC, prolajumokeoni commented
Hi @ntimanu 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have commit from your partner and there are webhint linter errorsin your pull request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-15 21:10 UTC, Shedrack-Sunday requested changes
Hello @ntimanu   👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Nice work with the use of classes✔️ 
- Good project setup ✔️ 
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-15 21:10 UTC, Shedrack-Sunday commented on script.js
> +    });
- [x] Nice effort you made here 👏 . However just like your previous implementations, you need to create  a stand alone function called `addBook` that takes a `title and author` as parameters. This should be a reusable component of your codebase 👍 

### Sample code:
```
addBook(title, author) {
    id = generateID(); // Optional: You can use title or author as  primary key instead of an ID in as long as you check for uniqueness
    this.books = this.books.concat({ title, author, author });
    return this.books; // You can  chose to return the book in a different getter method (see example - getBooks)
  }
```

2023-06-16 06:22 UTC, ntimanu commented on script.js
> +    });
@Shedrack-Sunday  I don't understand
Here I have used a function to create book, For the past project I have used object to do that. but now I changed to class and added a function to add books, Why would I need a parameter, what is wrong with my App?

2023-06-16 16:49 UTC, ntimanu commented on script.js
> +    });
Done

2023-06-16 22:11 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @ntimanu 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 11:23 UTC, merged